### PR TITLE
Add tests

### LINKED ISSUE #5: Add simple test
Just to verify that the exported rules are valid stylelint rules. Add travis config as well.

### PR DESCRIPTION
**Pull request by ghost**
Closes #5

- [x] Add travis badge

### CODE REVIEW

**Comment by ghost** [comment]
@mxstbr I haven't got the rights to enable this repo on travis, would you mind enabling it? Thanks!

**Comment by mxstbr** [comment]
Travis is enabled, if you add a Travis config it should trigger a build!

**Comment by mxstbr** [comment]
Oh I just saw you have already added one, if you force push it should trigger a build hopefully?

**Comment by mxstbr** [comment]
There we go, pushed a small README fix and we have a build now!

**Comment by mxstbr** [comment]
Test failure! :blush:

screen shot 2017-08-22 at 13 31 34

**Comment by mxstbr** [comment]
Whaaat it passes locally because the terminal is wide enough?!  🤦‍♂️

**Comment by mxstbr** [comment]
That's pretty stupid, I'm updating the snapshot with a slimmer snapshot but hot damn, tests shouldn't depend on the width of the users terminal!

**Review by mxstbr — APPROVED** [review]
Can we fix that terminal width thing? Otherwise this is ready to go!

**Comment by ghost** [comment]
> Whaaat it passes locally because the terminal is wide enough?! 🤦‍♂️

Oh wow, I've never seen that before. I'll see what I can do

**Comment by ghost** [comment]
Ok, fixed and merged. Simplified the tests so they just check if the correct rule has errored (instead of using snapshots).

**Pull request merged**
