### PR TITLE
Change name to stylelint-config-styled-components

### PR DESCRIPTION
**Pull request by ghost**
- [x] Update links in stylelint-processor-styled-components
- [x] Travis
- [x] Deprecate old module on npm
- [x] Publish package under new name, readd all owners again
- [x] Update changelog
- [x] Greenkeeper

### CODE REVIEW

**Comment by ghost** [comment]
I thought about incrementing the version, but it seems unnecessary. Is the changelog clear the way I formulated it?

**Review by mxstbr — APPROVED** [review]
PR LGTM!

**Comment by ghost** [comment]
@mxstbr I think the repo needs to be reactivated on travis btw.

**Comment by mxstbr** [comment]
Might've also broken greenkeeper haha, will get those fixed!

**Comment by ghost** [comment]
😄 Cool thanks!

**Comment by mxstbr** [comment]
Should be fixed if you push to this branch again?

**Comment by ghost** [comment]
@mxstbr Yup fixed 👍

**Pull request merged**
